### ISSUE TITLE
Duplicate entry creation

### ISSUE THREAD

**Issue by mgrolinger** [abhinavmarwaha/wrotto-app#2]
Hi,

the first entry of the journal is created twice.

## How to reproduce

1. Start the app
2. Press the + button on the lower left to open the dialog to create an entry
3. Fill in title and text and press a mood smiley
4. Press "Done" on the upper right corner
5. Press the pencil button to edit the entry you just created.
6. Change title, text and mood smiley
7. Press "Done" again
8. Press  the back button to return to the main application

### Expected
Expected to see 1 entry with the last title, text and mood smiley.

### Result
However, I see now two entries: the first generated and as a second the changed as a separate entry.

This also occurs if you continue to create and change an entry later on.

- Android 10
- Version 0.6.0.5
- Installed from fdroid

**Comment by abhinavmarwaha** [comment]
Does on restarting the app, the duplicate entry goes away?

**Comment by abhinavmarwaha** [comment]
Fixed it! Will be available in next update.
