### ISSUE TITLE
Dark mode incomplete 

### ISSUE THREAD

**Issue by mgrolinger** [abhinavmarwaha/wrotto-app#3]
Hi,

the dark mode is incomplete:

* On the main screen  the word 'All' is black and difficult to read as the lower menu bar.
* On the 'add entry' dialog the text color is black and difficult to read, the title is fine. 

- Android 10
- Version 0.6.0.5
- Installed from fdroid
![Screenshot_20210407-221451](https://user-images.githubusercontent.com/2290752/113928227-c6e77400-97ee-11eb-8f73-d25ef92ff4ea.jpg)

**Comment by abhinavmarwaha** [comment]
Thanks for the feedback!, fixed it. Will be available in the next update.
